### ISSUE TITLE
ds003643: mriqc: Can't use dataset with < 5 time points per voxel

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#10]
I'm getting this only for sub-EN059. I assume it's just an issue with the data for that subject but I thought I'd note it here in case there's a way to deal with this. Here's the full error:

>                      Currently running:
>                        * mriqc_wf.funcMRIQC.ComputeIQMs.outliers
>                        * mriqc_wf.funcMRIQC.SpatialNormalization.EPI2MNI
>                        * mriqc_wf.funcMRIQC.ICA
> 220428-21:37:12,249 nipype.workflow WARNING:
> 	 Storing result file without outputs
> 220428-21:37:12,251 nipype.workflow WARNING:
> 	 [Node] Error on "mriqc_wf.funcMRIQC.ComputeIQMs.outliers" (/scratch1/03201/jbwexler/work_dir/mriqc/ds003643_sub-EN059/mriqc_wf/funcMRIQC/ComputeIQMs/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003643-mriqc..sourcedata..raw..sub-EN059..func..sub-EN059_task-lppEN_run-16_echo-1_bold.nii.gz/outliers)
> 220428-21:37:13,521 nipype.workflow ERROR:
> 	 Node outliers.a27 failed to run on host c208-005.frontera.tacc.utexas.edu.
> 220428-21:37:13,521 nipype.workflow ERROR:
> 	 Saving crash info to /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds003643-mriqc/logs/crash-20220428-213713-jbwexler-outliers.a27-fcd640c5-dc89-4b1e-8f8a-b37fec0f3c0e.txt
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/afni/preprocess.py", line 1840, in _run_interface
>     runtime = super(OutlierCount, self)._run_interface(
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> 3dToutcount -fraction -mask /scratch1/03201/jbwexler/work_dir/mriqc/ds003643_sub-EN059/mriqc_wf/funcMRIQC/fMRIBrainMask/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003643-mriqc..sourcedata..raw..sub-EN059..func..sub-EN059_task-lppEN_run-16_echo-1_bold.nii.gz/afni_msk/sub-EN059_task-lppEN_run-16_echo-1_bold_valid_volreg_tstat_mask.nii.gz -qthr 0.00100 /scratch1/03201/jbwexler/work_dir/mriqc/ds003643_sub-EN059/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003643-mriqc..sourcedata..raw..sub-EN059..func..sub-EN059_task-lppEN_run-16_echo-1_bold.nii.gz/motion_correct/sub-EN059_task-lppEN_run-16_echo-1_bold_valid_volreg.nii.gz
> Standard output:
> 
> Standard error:
> ++ 3dToutcount: AFNI version=AFNI_22.0.17 (Mar 10 2022) [64-bit]
> *+ WARNING:   If you are performing spatial transformations on an oblique dset,
>   such as /scratch1/03201/jbwexler/work_dir/mriqc/ds003643_sub-EN059/mriqc_wf/funcMRIQC/fMRIBrainMask/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003643-mriqc..sourcedata..raw..sub-EN059..func..sub-EN059_task-lppEN_run-16_echo-1_bold.nii.gz/afni_msk/sub-EN059_task-lppEN_run-16_echo-1_bold_valid_volreg_tstat_mask.nii.gz,
>   or viewing/combining it with volumes of differing obliquity,
>   you should consider running:
>      3dWarp -deoblique
>   on this and  other oblique datasets in the same session.
>  See 3dWarp -help for details.
> ++ Oblique dataset:/scratch1/03201/jbwexler/work_dir/mriqc/ds003643_sub-EN059/mriqc_wf/funcMRIQC/fMRIBrainMask/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003643-mriqc..sourcedata..raw..sub-EN059..func..sub-EN059_task-lppEN_run-16_echo-1_bold.nii.gz/afni_msk/sub-EN059_task-lppEN_run-16_echo-1_bold_valid_volreg_tstat_mask.nii.gz is 11.889456 degrees from plumb.
> ++ 28405 voxels in the mask
> ++ Oblique dataset:/scratch1/03201/jbwexler/work_dir/mriqc/ds003643_sub-EN059/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds003643-mriqc..sourcedata..raw..sub-EN059..func..sub-EN059_task-lppEN_run-16_echo-1_bold.nii.gz/motion_correct/sub-EN059_task-lppEN_run-16_echo-1_bold_valid_volreg.nii.gz is 11.889456 degrees from plumb.
> ** Can't use dataset with < 5 time points per voxel!
> Return code: 1

**Comment by jbwexler** [comment]
I just reran and it still fails.
