### ISSUE TITLE
ds001942-mriqc: Out of Memory

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#12]
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> fast -t 1 -o segment -g -S 1 /scratch1/03201/jbwexler/work_dir/mriqc/ds001942_sub-S01/mriqc_wf/anatMRIQC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds001942-mriqc..sourcedata..raw..sub-S01..ses-SES01..anat..sub-S01_ses-SES01_acq-ShortInv_run-02_T1w.nii.gz/segmentation/sub-S01_ses-SES01_acq-ShortInv_run-02_T1w_conformed_calc.nii.gz
> Standard output:
> 
> Standard error:
> Image Exception : #99 :: Out of memory
> terminate called after throwing an instance of 'RBD_COMMON::BaseException'
> Aborted
> Return code: 134

**Comment by jbwexler** [comment]
Resolved by running one subject per node.
