### ISSUE TITLE
ds001734-fmriprep: "numpy.core._exceptions._ArrayMemoryError"

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#16]
Happened for only around 4 subjects, including sub-109 and sub-113.

> Node: fmriprep_wf.single_subject_036_wf.func_preproc_task_MGT_run_03_wf.unwarp_wf.resample
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds001734_sub-036/fmriprep_wf/single
> _subject_036_wf/func_preproc_task_MGT_run_03_wf/unwarp_wf/resample
> 
> Node inputs:
> 
> in_coeff = <undefined>
> in_data = <undefined>
> in_xfms = <undefined>
> num_threads = 7
> pe_dir = <undefined>
> ro_time = <undefined>
> 
> concurrent.futures.process._RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
>     r = call_item.fn(*call_item.args, **call_item.kwargs)
>   File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
>     return [fn(*args) for args in chunk]
>   File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
>     return [fn(*args) for args in chunk]
>   File "/opt/conda/lib/python3.8/site-packages/sdcflows/interfaces/bspline.py", line 536, in _b0_
> resampler
>     if unwarp.fit(data):
>   File "/opt/conda/lib/python3.8/site-packages/sdcflows/transform.py", line 92, in fit
>     vsm = (np.squeeze(np.hstack(coeffs).T) @ sparse_vstack(weights)).reshape(
>   File "/opt/conda/lib/python3.8/site-packages/scipy/sparse/construct.py", line 501, in vstack
>     return bmat([[b] for b in blocks], format=format, dtype=dtype)
>   File "/opt/conda/lib/python3.8/site-packages/scipy/sparse/construct.py", line 621, in bmat
>     row[idx] = B.row + row_offsets[i]
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 325. MiB for an array with shape (85071360,) and data type int32
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _ru
> n_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _ru
> n_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/sdcflows/interfaces/bspline.py", line 321, in _run
> _interface
>     ) = zip(*outputs)
>   File "/opt/conda/lib/python3.8/concurrent/futures/process.py", line 484, in _chain_from_iterabl
> e_of_lists
>     for element in iterable:
>   File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
>     yield fs.pop().result()
>   File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
>     return self.__get_result()
>   File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
>     raise self._exception
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 325. MiB for an array with shape (85
> 071360,) and data type int32

**Comment by jbwexler** [comment]
Yep, solved by rerunning.
