### ISSUE TITLE
ds003612-fmriprep: Error: short read, file may be truncated

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#21]
Got this error for just two subjects.

> Node: fmriprep_wf.single_subject_108TUSW011026_wf.func_preproc_ses_1_task_execution_acq_Fs2_run_02_wf.bold_split
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds003612_sub-108TUSW011026/fmriprep_wf/single_subject_108TUSW011026_wf/func_preproc_ses_1_task_execution_acq_Fs2_run_02_wf/bold_split
> 
> Node inputs:
> 
> args = <undefined>
> dimension = t
> environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
> Node: fmriprep_wf.single_subject_108TUSW011026_wf.func_preproc_ses_1_task_execution_acq_Fs2_run_02_wf.bol
> d_split
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds003612_sub-108TUSW011026/fmriprep_wf/sing
> le_subject_108TUSW011026_wf/func_preproc_ses_1_task_execution_acq_Fs2_run_02_wf/bold_split
> 
> Node inputs:
> 
> args = <undefined>
> dimension = t
> environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
> in_file = /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003612-fmriprep/sourcedata/raw/sub-108TUSW011026/ses-1/func/sub-108TUSW011026_ses-1_task-execution_acq-Fs2_run-02_bold.nii.gz
> out_base_name = <undefined>
> output_type = NIFTI_GZ
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> fslsplit /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003612-fmriprep/sourcedata/raw/sub-108TUSW011026/ses-1/func/sub-108TUSW011026_ses-1_task-execution_acq-Fs2_run-02_bold.nii.gz -t
> Standard output:
> 
> Standard error:
> Image Exception : #22 :: Failed to read volume /scratch1/03201/jbwexler/openneuro_derivatives/derivatives
> /fmriprep/ds003612-fmriprep/sourcedata/raw/sub-108TUSW011026/ses-1/func/sub-108TUSW011026_ses-1_task-exec
> ution_acq-Fs2_run-02_bold.nii.gz
> Error : Error: short read, file may be truncated
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Failed to read volume /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds00
> 3612-fmriprep/sourcedata/raw/sub-108TUSW011026/ses-1/func/sub-108TUSW011026_ses-1_task-execution_acq-Fs2_
> run-02_bold.nii.gz
> Error : Error: short read, file may be truncated
> Aborted
> Return code: 134

**Comment by jbwexler** [comment]
@effigies It looks like that func image is [corrupted](https://openneuro.org/datasets/ds003612/versions/1.0.2/file-display/sub-108TUSW011026:ses-1:func:sub-108TUSW011026_ses-1_task-imagery_acq-Fs2_run-01_bold.nii.gz). Does it make sense to bids_ignore that file or something and rerun that sub?

**Comment by effigies** [comment]
Missed this. Yes, we should ignore this file. Easier to just delete it from the dataset or set up a bids-filter-file that will include everything else.
