### ISSUE TITLE
ds000116-fmriprep: The specified MELODIC directory does not contain the required files to run ICA-AROMA

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#22]
Just for sub-04:

> Node: fmriprep_wf.single_subject_04_wf.func_preproc_task_auditoryoddballwithbuttonresponsetotargetstimuli_run_02_wf.ica_aroma_wf.ica_aroma
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds000116_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_task_auditoryoddballwithbuttonresponsetotargetstimuli_run_02_wf/ica_aroma_wf/ica_aroma
> 
> Node inputs:
> 
> TR = 2.0
> args = -np
> compress_report = auto
> denoise_type = nonaggr
> dim = <undefined>
> environ = {}
> feat_dir = <undefined>
> fnirt_warp_file = <undefined>
> in_file = <undefined>
> mask = <undefined>
> mat_file = <undefined>
> melodic_dir = <undefined>
> motion_parameters = <undefined>
> out_dir = out
> out_report = ica_aroma_reportlet.svg
> report_mask = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_ex
> ception
>     raise RuntimeError(
> RuntimeError: Command:
> ICA_AROMA.py -tr 2.000 -np -den nonaggr -i /scratch1/03201/jbwexler/work_dir/fmriprep/ds000116_sub-04
> /fmriprep_wf/single_subject_04_wf/func_preproc_task_auditoryoddballwithbuttonresponsetotargetstimuli_
> run_02_wf/ica_aroma_wf/smooth/vol0000_xform-00000_clipped_merged_cut_smooth.nii.gz -m /scratch1/03201
> /jbwexler/work_dir/fmriprep/ds000116_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_task_audito
> ryoddballwithbuttonresponsetotargetstimuli_run_02_wf/bold_std_trans_wf/_std_target_MNI152NLin6Asym.re
> s2/mask_std_tfm/vol0000_xform-00000_clipped_merged_average_corrected_brain_mask_maths_trans.nii.gz -m
> eldir /scratch1/03201/jbwexler/work_dir/fmriprep/ds000116_sub-04/fmriprep_wf/single_subject_04_wf/fun
> c_preproc_task_auditoryoddballwithbuttonresponsetotargetstimuli_run_02_wf/ica_aroma_wf/melodic -mc /s
> cratch1/03201/jbwexler/work_dir/fmriprep/ds000116_sub-04/fmriprep_wf/single_subject_04_wf/func_prepro
> c_task_auditoryoddballwithbuttonresponsetotargetstimuli_run_02_wf/bold_hmc_wf/normalize_motion/motion
> _params.txt -o /scratch1/03201/jbwexler/work_dir/fmriprep/ds000116_sub-04/fmriprep_wf/single_subject_
> 04_wf/func_preproc_task_auditoryoddballwithbuttonresponsetotargetstimuli_run_02_wf/ica_aroma_wf/ica_a
> roma/out
> Standard output:
> 
> ------------------------------- RUNNING ICA-AROMA -------------------------------
> --------------- 'ICA-based Automatic Removal Of Motion Artifacts' ---------------
> 
> Step 1) MELODIC
>   - The specified MELODIC directory does not contain the required files to run ICA-AROMA. MELODIC wil
> l be run seperately.
> Standard error:
>   No convergence after 500 steps
> Traceback (most recent call last):
>   File "/opt/ICA-AROMA/ICA_AROMA.py", line 204, in <module>
>     aromafunc.runICA(fslDir, inFile, outDir, melDir, mask, dim, TR)
>   File "/opt/ICA-AROMA/ICA_AROMA_functions.py", line 94, in runICA
>     nrICs = int(float(subprocess.getoutput(cmd)))
> ValueError: could not convert string to float: 'Image Exception : #63 :: No image files match: /scrat
> ch1/03201/jbwexler/work_dir/fmriprep/ds000116_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_ta
> sk_auditoryoddballwithbuttonresponsetotargetstimuli_run_02_wf/ica_aroma_wf/ica_aroma/out/melodic.ica/
> melodic_IC\nNo image files match: /scratch1/03201/jbwexler/work_dir/fmriprep/ds000116_sub-04/fmriprep
> _wf/single_subject_04_wf/func_preproc_task_auditoryoddballwithbuttonresponsetotargetstimuli_run_02_wf
> /ica_aroma_wf/ica_aroma/out/melodic.ica/melodic_IC'
> Return code: 1
> (END)

**Comment by effigies** [comment]
Likely a filesystem sync issue. I would retry. Does `/scratch1/03201/jbwexler/work_dir/fmriprep/ds000116_sub-04/fmriprep_wf/single_subject_04_wf/func_preproc_task_auditoryoddballwithbuttonresponsetotargetstimuli_run_02_wf/ica_aroma_wf/ica_aroma/out/melodic.ica/melodic_IC` exist?
