### ISSUE TITLE
ds002185-mriqc: Segmentation fault

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#26]
Only for two subjects. Rerunning didn't solve it.

> Traceback (most recent call last):
>   File "/opt/conda/bin/mriqc", line 8, in <module>
>     sys.exit(main())
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/cli/run.py", line 158, in main
>     mriqc_wf.run(**_plugin)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/engine/plugin.py", line 184, in run
>     self._clean_queue(jobid, graph, result=result)
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/engine/plugin.py", line 256, in _clean_queue
>     raise RuntimeError("".join(result["traceback"]))
> RuntimeError: Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/engine/plugin.py", line 60, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_in
> terface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_co
> mmand
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 419, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/fsl/preprocess.py", line 164, in _ru
> n_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 741, in raise_ex
> ception
>     raise RuntimeError(
> RuntimeError: Command:
> bet /scratch1/03201/jbwexler/work_dir/mriqc/ds002185_sub-14/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file
> _..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002185-mriqc..sourcedata..
> raw..sub-14..anat..sub-14_acq-space_T2w.nii.gz/post_n4/clipped_corrected.nii.gz /scratch1/03201/jbwex
> ler/work_dir/mriqc/ds002185_sub-14/mriqc_wf/anatMRIQC/HeadMaskWorkflow/_in_file_..scratch1..03201..jb
> wexler..openneuro_derivatives..derivatives..mriqc..ds002185-mriqc..sourcedata..raw..sub-14..anat..sub-14_acq-space_T2w.nii.gz/fsl_bet/clipped_corrected_brain.nii.gz -A
> Standard output:
> 
> Standard error:
> Segmentation fault
> Return code: 0
> 
> (END)

**Comment by jbwexler** [comment]
Recently got a similar error for all subjects in ds003823:

> 
> Traceback (most recent call last):
>   File "/opt/conda/bin/mriqc", line 8, in <module>
>     sys.exit(main())
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/cli/run.py", line 167, in main
>     mriqc_wf.run(**_plugin)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 184, in run
>     self._clean_queue(jobid, graph, result=result)
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 256, in _clean_queue
>     raise RuntimeError("".join(result["traceback"]))
> RuntimeError: Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
>     raise NodeExecutionError(msg)
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node fsl_bet.
> 
> Cmdline:
>         bet clipped_corrected.nii.gz clipped_corrected_brain.nii.gz -A
> Stdout:
> 
> Stderr:
>         Segmentation fault
> Traceback:
>         Traceback (most recent call last):
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
>             runtime = self._run_interface(runtime)
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/fsl/preprocess.py", line 165, in _run_interface
>             self.raise_exception(runtime)
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 686, in raise_exception
>             raise RuntimeError(
>         RuntimeError: Command:
>         bet clipped_corrected.nii.gz clipped_corrected_brain.nii.gz -A
>         Standard output:
> 
>         Standard error:
>         Segmentation fault
>         Return code: 0

**Comment by effigies** [comment]
I would look at the files that it failed on, e.g. `/scratch1/03201/jbwexler/work_dir/mriqc/ds002185_sub-14/mriqc_wf/anatMRIQC/synthstrip_wf/_in_file
_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002185-mriqc..sourcedata..
raw..sub-14..anat..sub-14_acq-space_T2w.nii.gz/post_n4/clipped_corrected.nii.gz`. Doesn't look like it's still on TACC. If there's nothing visually wrong with it, I'd try running BET on it locally.

**Comment by jbwexler** [comment]
Looks like the issue here is due to some anatomical files having a small fov: https://openneuro.org/datasets/ds003823/versions/1.3.3/file-display/sub-5001:ses-post:anat:sub-5001_ses-post_acq-lc_T1w.nii.gz

Is there a way to deal with that in mriqc? Or just ignore them?

**Comment by effigies** [comment]
Need to use `--bids-filter-file` with contents like:

```json
{
  "t1w": {
    "datatype": "anat",
    "suffix": "T1w",
    "part": ["mag", null],
    "acquistion": "wholebrain",
  }
}
```

Pass as `--bids-filter-file code/bids-filters.json` or similar. When making a new filter, start with queries in:

https://github.com/nipreps/niworkflows/blob/c0caa623358ec71d2432e65bec40be8a28080264/niworkflows/utils/bids.py#L34-L45

Then add refinements.

**Comment by effigies** [comment]
For ds002185, pass `-m T1w bold`. Or a query that can't match anything:

```json
{
  "t2w": {"datatype": None, "suffix": "T2w"}
}
```
