### ISSUE TITLE
ds000253-fmriprep: nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node autorecon1.

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#29]
Got this error for about half of subjects

> Node: fmriprep_22_0_wf.single_subject_20_wf.anat_preproc_wf.surface_recon_wf.autorecon1
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds000253_sub-20/fmriprep_22_0_wf/single
> _subject_20_wf/anat_preproc_wf/surface_recon_wf/autorecon1
> 
> Node inputs:
> 
> FLAIR_file = <undefined>
> T1_files = <undefined>
> T2_file = <undefined>
> args = <undefined>
> big_ventricles = <undefined>
> brainstem = <undefined>
> directive = autorecon1
> environ = {}
> expert = <undefined>
> flags = <undefined>
> hemi = <undefined>
> hippocampal_subfields_T1 = <undefined>
> hippocampal_subfields_T2 = <undefined>
> hires = <undefined>
> mprage = <undefined>
> mri_aparc2aseg = <undefined>
> mri_ca_label = <undefined>
> mri_ca_normalize = <undefined>
> mri_ca_register = <undefined>
> mri_edit_wm_with_aseg = <undefined>
> mri_em_register = <undefined>
> mri_fill = <undefined>
> mri_mask = <undefined>
> mri_normalize = <undefined>
> mri_pretess = <undefined>
> mri_remove_neck = <undefined>
> mri_segment = <undefined>
> mri_segstats = <undefined>
> mri_tessellate = <undefined>
> mri_watershed = <undefined>
> mris_anatomical_stats = <undefined>
> mris_ca_label = <undefined>
> mris_fix_topology = <undefined>
> mris_inflate = <undefined>
> mris_make_surfaces = <undefined>
> mris_register = <undefined>
> mris_smooth = <undefined>
> mris_sphere = <undefined>
> mris_surf2vol = <undefined>
> mrisp_paint = <undefined>
> openmp = 7
> parallel = <undefined>
> steps = <undefined>
> subject_id = recon_all
> subjects_dir = <undefined>
> talairach = <undefined>
> use_FLAIR = <undefined>
> use_T2 = <undefined>
> xopts = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run
> _node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_in
> terface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_co
> mmand
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node autorecon1.
> 
> RuntimeError: subprocess exited with code 1.

**Comment by effigies** [comment]
We'll need to see the recon logs. For the future, if you use 22.0.2+, we should get better error reporting.
