### ISSUE TITLE
ds001242-fmriprep: IndexError: list index out of range

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#30]
Got this for every subject.

> Process Process-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/lib/python3.9/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
>     retval["workflow"] = init_fmriprep_wf()
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 89, in init_fmriprep_wf
>     single_subject_wf = init_single_subject_wf(subject_id)
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/base.py", line 374, in init_single_subject_wf
>     func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/bold/base.py", line 440, in init_func_preproc_wf
>     func_derivatives_wf = init_func_derivatives_wf(
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/bold/outputs.py", line 164, in init_func_derivatives_wf
>     timing_parameters = prepare_timing_parameters(metadata)
>   File "/opt/conda/lib/python3.9/site-packages/fmriprep/workflows/bold/outputs.py", line 96, in prepare_timing_parameters
>     TA = st[-1] + (st[1] - st[0])  # Final slice onset - slice duration
> IndexError: list index out of range

**Comment by effigies** [comment]
https://github.com/OpenNeuroDatasets/ds001242/blob/master/sub-01/func/sub-01_task-fearlearning_bold.json#L6:

```JSON
    "SliceTiming": [],
```

This should probably be a bids validation error, and fMRIPrep should catch it, but you can use `--ignore slicetiming` for this dataset.
