### ISSUE TITLE
ds003126-fmriprep: nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _midthickness0.

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#31]
Got this for every subject.

> Node: _midthickness0
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds003126_sub-047EPKL012074/fmriprep_22_0_wf/single_subject_047EPKL012074_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/midthickness/mapflow/_midthickness0
> 
> Node inputs:
> 
> args = <undefined>
> distance = 0.5
> dt = <undefined>
> environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects'}
> graymid = <undefined>
> in_file = /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003126-fmriprep/sourcedata/freesurfer/sub-047EPKL012074/surf/lh.smoothwm
> nsurfaces = <undefined>
> out_name = midthickness
> pial = <undefined>
> smooth_averages = <undefined>
> sphere = sphere
> spring = <undefined>
> subjects_dir = /opt/freesurfer/subjects
> thickness = True
> thickness_name = <undefined>
> write_iterations = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _midthickness0.
> 
> RuntimeError: subprocess exited with code 134.
> ...skipping...
> Node: _midthickness0
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds003126_sub-047EPKL012074/fmriprep_22_0_wf/single_subject_047EPKL012074_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/midthickness/mapflow/_midthickness0
> 
> Node inputs:
> 
> args = <undefined>
> distance = 0.5
> dt = <undefined>
> environ = {'SUBJECTS_DIR': '/opt/freesurfer/subjects'}
> graymid = <undefined>
> in_file = /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/fmriprep/ds003126-fmriprep/sourcedata/freesurfer/sub-047EPKL012074/surf/lh.smoothwm
> nsurfaces = <undefined>
> out_name = midthickness
> pial = <undefined>
> smooth_averages = <undefined>
> sphere = sphere
> spring = <undefined>
> subjects_dir = /opt/freesurfer/subjects
> thickness = True
> thickness_name = <undefined>
> write_iterations = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _midthickness0.
> 
> RuntimeError: subprocess exited with code 134.

**Comment by effigies** [comment]
Seems to be https://github.com/nipreps/smriprep/issues/294. We didn't really track that down, but looks like a good one to debug manually.
