### ISSUE TITLE
ds002411-fmriprep: transform_Warped.nii.gz not found

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#32]
For about half the subjects:

> Node: fmriprep_22_0_wf.single_subject_01_wf.func_preproc_task_ProgramCategorization_run_06_wf.co
> eff2epi_wf.coregister
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds002411_sub-01/fmriprep_22_0_wf/s
> ingle_subject_01_wf/func_preproc_task_ProgramCategorization_run_06_wf/coeff2epi_wf/coregister
> 
> Node inputs:
> 
> args = <undefined>
> collapse_output_transforms = True
> convergence_threshold = [1e-07, 1e-08]
> convergence_window_size = [5, 3]
> dimension = 3
> environ = {'NSLOTS': '7'}
> fixed_image = <undefined>
> fixed_image_mask = <undefined>
> fixed_image_masks = <undefined>
> float = <undefined>
> initial_moving_transform = <undefined>
> initial_moving_transform_com = 1
> initialize_transforms_per_stage = False
> interpolation = LanczosWindowedSinc
> interpolation_parameters = <undefined>
> invert_initial_moving_transform = <undefined>
> metric = ['Mattes', 'Mattes']
> metric_item_trait = <undefined>
> metric_stage_trait = <undefined>
> metric_weight = [1.0, 1.0]
> metric_weight_item_trait = 1.0
> metric_weight_stage_trait = <undefined>
> moving_image = <undefined>
> moving_image_mask = <undefined>
> moving_image_masks = <undefined>
> num_threads = 7
> number_of_iterations = [[50], [20]]
> output_inverse_warped_image = <undefined>
> output_transform_prefix = transform
> output_warped_image = True
> radius_bins_item_trait = 5
> radius_bins_stage_trait = <undefined>
> radius_or_number_of_bins = [32, 32]
> random_seed = <undefined>
> restore_state = <undefined>
> restrict_deformation = <undefined>
> sampling_percentage = [0.25, 0.5]
> sampling_percentage_item_trait = <undefined>
> sampling_percentage_stage_trait = <undefined>
> sampling_strategy = ['Random', 'Random']
> sampling_strategy_item_trait = <undefined>
> sampling_strategy_stage_trait = <undefined>
> save_state = <undefined>
> shrink_factors = [[2], [1]]
> sigma_units = ['mm', 'mm']
> smoothing_sigmas = [[8.0], [2.0]]
> transform_parameters = [(0.1,), (0.1,)]
> transforms = ['Rigid', 'Rigid']
> use_estimate_learning_rate_once = [True, False]
> use_histogram_matching = [True, True]
> verbose = False
> winsorize_lower_quantile = 0.001
> winsorize_upper_quantile = 0.999
> write_composite_transform = False
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node coregister.
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nibabel/loadsave.py", line 90, in load
>     stat_result = os.stat(filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002411_sub-01/fmriprep_22_0_wf/single_subject_01_wf/func_preproc_task_ProgramCategorization_run_06_wf/coeff2epi_wf/coregister/transform_Warped.nii.gz'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/fixes.py", line 110, in _run_interface
>     _copyxform(
>   File "/opt/conda/lib/python3.9/site-packages/niworkflows/utils/images.py", line 79, in _copyxform
>     resampled = nb.load(out_image, mmap=False)
>   File "/opt/conda/lib/python3.9/site-packages/nibabel/loadsave.py", line 92, in load
>     raise FileNotFoundError(f"No such file or no access: '{filename}'")
> FileNotFoundError: No such file or no access: '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002411_sub-01/fmriprep_22_0_wf/single_subject_01_wf/func_preproc_task_ProgramCategorization_run_06_wf/coeff2epi_wf/coregister/transform_Warped.nii.gz'

**Comment by effigies** [comment]
This is almost certainly a filesystem sync issue. Rerunning should resolve.

**Comment by effigies** [comment]
Looks like https://github.com/nipreps/fmriprep/issues/2878. This could be a deeper sdcflows issue.

**Comment by liuzhenqi77** [comment]
I'm seeing the same error on ds004078 subject-01 using fmriprep 22.0.0.

**Comment by jbwexler** [comment]
@effigies Do we have a solution for this yet?

**Comment by effigies** [comment]
No, I haven't figured out what led to this. Did you try rerunning?

**Comment by jbwexler** [comment]
I haven't, I can try that.

**Comment by jbwexler** [comment]
Hmm rerunning didn't seem to solve this. Perhaps I need to delete the old work dirs?
