### ISSUE TITLE
ds000051-fmriprep: 177422 Segmentation fault 

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#33]
Just for sub-03.

> 221013-23:06:59,933 nipype.workflow CRITICAL:
>          fMRIPrep failed: Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node skullstrip_first_pass.
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/fsl/preprocess.py", line 165, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 686, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> bet sub-03_task-abstractconcretejudgment_run-04_bold_average_corrected.nii.gz sub-03_task-abstractconcretejudgment_run-04_bold_average_correc
> ted_brain.nii.gz -f 0.20 -m
> Standard output:
> /opt/fsl-6.0.5.1/bin/bet failed during command:sub-03_task-abstractconcretejudgment_run-04_bold_average_corrected.nii.gz sub-03_task-abstract
> concretejudgment_run-04_bold_average_corrected_brain.nii.gz -f 0.20 -m
> Standard error:
> /opt/fsl-6.0.5.1/bin/bet: line 399: 177422 Segmentation fault      ${FSLDIR}/bin/bet2 $IN $OUT $bet2opts
> Return code: 1

**Comment by jbwexler** [comment]
@effigies Any thoughts on this? I recently got a similar issue for one subject in ds000224-fmriprep

**Comment by jbwexler** [comment]
This was solved thanks to @effigies' solution:

> `/scratch1/03201/jbwexler/work_dir/fmriprep/ds000224_sub-MSC03/fmriprep_22_0_wf/single_subject_MSC03_wf/func_preproc_ses_func06_task_memoryfaces_wf/final_boldref_wf/enhance_and_skullstrip_bold_wf/n4_correct` is corrupted. I tried re-running the command, and it seemed to work (generating test.nii.gz in that directory). I think if you delete that directory and re-run it should work.
