### ISSUE TITLE
ds002422: Exception raised while executing Node ICA

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#37]
Several subjects in this dataset prouced ICA-related errors.

> Node: mriqc_wf.funcMRIQC.ICA
> Working directory: /scratch1/03201/jbwexler/work_dir/mriqc/ds002242_sub-3023/mriqc_wf/funcMRIQC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002242-mriqc..sourcedata..raw..sub-3023..func..sub-3023_task-stt_run-1_bold.nii.gz/ICA
> 
> Node inputs:
> 
> ICs = <undefined>
> approach = <undefined>
> args = <undefined>
> bg_image = <undefined>
> bg_threshold = <undefined>
> compress_report = False
> cov_weight = <undefined>
> dim = <undefined>
> dim_est = <undefined>
> environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
> epsilon = <undefined>
> epsilonS = <undefined>
> in_files = <undefined>
> log_power = <undefined>
> mask = <undefined>
> max_restart = <undefined>
> maxit = <undefined>
> migp = <undefined>
> migpN = <undefined>
> migp_factor = <undefined>
> migp_shuffle = <undefined>
> mix = <undefined>
> mm_thresh = <undefined>
> no_bet = True
> no_mask = True
> no_mm = True
> non_linearity = <undefined>
> num_ICs = <undefined>
> out_all = <undefined>
> out_dir = <undefined>
> out_mean = <undefined>
> out_orig = <undefined>
> out_pca = <undefined>
> out_report = melodic_reportlet.svg
> out_stats = <undefined>
> out_unmix = <undefined>
> out_white = <undefined>
> output_type = NIFTI_GZ
> pbsc = <undefined>
> rem_cmp = <undefined>
> remove_deriv = <undefined>
> report = <undefined>
> report_maps = <undefined>
> report_mask = <undefined>
> s_con = <undefined>
> s_des = <undefined>
> sep_vn = <undefined>
> sep_whiten = <undefined>
> smode = <undefined>
> t_con = <undefined>
> t_des = <undefined>
> tr_sec = <undefined>
> update_mask = <undefined>
> var_norm = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node ICA.
> 
> RuntimeError: subprocess exited with code 134.

**Comment by jbwexler** [comment]
Same error for several subjects in ds001926-mriqc.

**Comment by jbwexler** [comment]
For several subjects in ds003701-mriqc too.
