### ISSUE TITLE
ds002684-mriqc: "ValueError: The number of observations cannot be determined on an empty distance matrix."

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#39]
For 2/4 subjects:

> Node: mriqc_wf.funcMRIQC.ReportsWorkflow.BigPlot
> Working directory: /scratch1/03201/jbwexler/work_dir/mriqc/ds002684_sub-02/mriqc_wf/funcMRIQC/Report
> sWorkflow/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds002684-
> mriqc..sourcedata..raw..sub-02..ses-GE..func..sub-02_ses-GE_task-prf_run-04_bold.nii/BigPlot
> 
> Node inputs:
> 
> drop_trs = 0
> dvars = <undefined>
> fd = <undefined>
> fd_thres = 0.2
> in_func = <undefined>
> in_segm = <undefined>
> in_spikes_bg = <undefined>
> outliers = <undefined>
> tr = None
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node BigPlot.
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.9/site-packages/niworkflows/interfaces/plotting.py", line 99, in _run_interface
>     fig = fMRIPlot(
>   File "/opt/conda/lib/python3.9/site-packages/niworkflows/viz/plots.py", line 129, in plot
>     plot_carpet(
>   File "/opt/conda/lib/python3.9/site-packages/niworkflows/viz/plots.py", line 236, in plot_carpet
>     children, _, n_leaves, _, distances = ward_tree(roi_data, return_distance=True)
>   File "/opt/conda/lib/python3.9/site-packages/sklearn/cluster/_agglomerative.py", line 270, in ward_tree
>     out = hierarchy.ward(X)
>   File "/opt/conda/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 834, in ward
>     return linkage(y, method='ward', metric='euclidean')
>   File "/opt/conda/lib/python3.9/site-packages/scipy/cluster/hierarchy.py", line 1068, in linkage
>     n = int(distance.num_obs_y(y))
>   File "/opt/conda/lib/python3.9/site-packages/scipy/spatial/distance.py", line 2573, in num_obs_y
>     raise ValueError("The number of observations cannot be determined on "
> ValueError: The number of observations cannot be determined on an empty distance matrix.

**Comment by jbwexler** [comment]
Also for 2/4 subjects in ds003427.

**Comment by jbwexler** [comment]
And for 3/7 subjects in ds002295.

**Comment by effigies** [comment]
Should be resolved in https://github.com/nipreps/niworkflows/pull/783, so the next MRIQC release that includes niworkflows 1.7.4 or higher should be fixed.
