### ISSUE TITLE
ds000107: FATAL ERROR: 3dvolreg fails: base image has 0 nonzero voxels (< 100)

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#4]
I got the following error for two (out of many) subjects when running fmriprep on ds000107. I checked the original image sourcedata/raw/sub-18/func/sub-18_task-onebacktask_run-02_bold.nii.gz and surprisingly it seems load fine with nibabel and fsleyes. Though I couldn’t get it to load on openneuro with papaya.

> Traceback (most recent call last):
>   File "/opt/conda/bin/mriqc", line 8, in <module>
>     sys.exit(main())
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/cli/run.py", line 95, in main
>     mriqc_wf.run(**config.nipype.get_plugin())
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 164, in run
>     self._clean_queue(jobid, graph, result=result)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
>     raise RuntimeError("".join(result["traceback"]))
> RuntimeError: Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/afni/base.py", line 124, in _run_interface
>     return super(AFNICommandBase, self)._run_interface(
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> 3dvolreg -Fourier -twopass -1Dfile sub-18_task-onebacktask_run-02_bold.1D -1Dmatrix_save sub-18_task-onebacktask_run-02_bold.aff12.1D -prefix sub-18_task-onebacktask_run-02_bold_volreg.nii.gz -zpad 4 -maxdisp1D sub-18_task-onebacktask_run-02_bold_md.1D /scratch1/03201/jbwexler/work_dir/mriqc/ds000107_sub-18/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds000107-mriqc..sourcedata..raw..sub-18..func..sub-18_task-onebacktask_run-02_bold.nii.gz/motion_correct/sub-18_task-onebacktask_run-02_bold.nii.gz
> Standard output:
> ​
> Standard error:
> ++ 3dvolreg: AFNI version=AFNI_21.2.06 (Sep  1 2021) [64-bit]
> ++ Authored by: RW Cox
> ++ Coarse del was 10, replaced with 3
> ++ WARNING: nifti_read_buffer(/scratch1/03201/jbwexler/work_dir/mriqc/ds000107_sub-18/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds000107-mriqc..sourcedata..raw..sub-18..func..sub-18_task-onebacktask_run-02_bold.nii.gz/motion_correct/sub-18_task-onebacktask_run-02_bold.nii.gz):
>    data bytes needed = 286720
>    data bytes input  = -1
>    number missing    = 286721 (set to 0)
> ** NIFTI load bricks: cannot read brick 165 from '/scratch1/03201/jbwexler/work_dir/mriqc/ds000107_sub-18/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds000107-mriqc..sourcedata..raw..sub-18..func..sub-18_task-onebacktask_run-02_bold.nii.gz/motion_correct/sub-18_task-onebacktask_run-02_bold.nii.gz'
> ** FATAL ERROR: 3dvolreg fails: base image has 0 nonzero voxels (< 100)
> ** Program compile date = Sep  1 2021
> Return code: 1

**Comment by jbwexler** [comment]
Got this error for two subs in ds002675-fmriprep

**Comment by jbwexler** [comment]
Also three subs in ds002306-fmriprep

**Comment by jbwexler** [comment]
@effigies

**Comment by effigies** [comment]
@jbwexler I'll need the traceback for fmriprep. It's not going to match the mriqc one.

**Comment by jbwexler** [comment]
Here's an example error log for ds002306:

> Node: fmriprep_wf.single_subject_01_wf.func_preproc_task_training_run_12_wf.final_boldref_wf.gen_avg
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds002306_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_task_training_run_12_wf/final_boldref_wf/gen_avg
> 
> Node inputs:
> 
> in_file = <undefined>
> mc_method = AFNI
> nonnegative = True
> t_mask = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/images.py", line 322, in _run_interface
>     res = Volreg(
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
>     runtime = self._run_interface(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/afni/base.py", line 124, in _run_interface
>     return super(AFNICommandBase, self)._run_interface(
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
>     self.raise_exception(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 749, in raise_exception
>     raise RuntimeError(
> RuntimeError: Command:
> 3dvolreg -Fourier -twopass -1Dfile vol0000_unwarped_merged_sliced.1D -1Dmatrix_save vol0000_unwarped_merged_sliced.aff12.1D -prefix vol0000_unwarped_merged_sliced_volreg.nii.gz -zpad 4 -maxdisp1D vol0000_unwarped_merged_sliced_md.1D /scratch1/03201/jbwexler/work_dir/fmriprep/ds002306_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_task_training_run_12_wf/final_boldref_wf/gen_avg/vol0000_unwarped_merged_sliced.nii.gz
> Standard output:
> 
> Standard error:
> ++ 3dvolreg: AFNI version=AFNI_22.1.02 (Apr  6 2022) [64-bit]
> ++ Authored by: RW Cox
> ESC[7m*+ WARNING:ESC[0m   If you are performing spatial transformations on an oblique dset,
>   such as /scratch1/03201/jbwexler/work_dir/fmriprep/ds002306_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_task_training_run_12_wf/final_boldref_wf/gen_avg/vol0000_unwarped_merged_sliced.nii.gz,
>   or viewing/combining it with volumes of differing obliquity,
>   you should consider running:
>      3dWarp -deoblique
>   on this and  other oblique datasets in the same session.
>  See 3dWarp -help for details.
> ++ Oblique dataset:/scratch1/03201/jbwexler/work_dir/fmriprep/ds002306_sub-01/fmriprep_wf/single_subject_01_wf/func_preproc_task_training_run_12_wf/final_boldref_wf/gen_avg/vol0000_unwarped_merged_sliced.nii.gz is 1.780153 degrees from plumb.
> ++ Coarse del was 10, replaced with 7
> ESC[7m** FATAL ERROR:ESC[0m 3dvolreg fails: base image has 0 nonzero voxels (< 100)
> ** Program compile date = Apr  6 2022
> Return code: 1

**Comment by ruben-stanford** [comment]
I'm also having this issue when running fMRIPrep on some task data. Are there any updates for this?
