### ISSUE TITLE
ds000238-mriqc: "Exception raised while executing Node motion_correct"

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#42]
This just occurred for one subject. Rerunning didn't solve it.

> Node: mriqc_wf.funcMRIQC.fMRI_HMC.motion_correct
> Working directory: /scratch1/03201/jbwexler/work_dir/mriqc/ds000238_sub-22/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds000238-mriqc..sourcedata..raw..sub-22..func..sub-22_task-slow12_run-1_bold.nii.gz/motion_correct
> 
> Node inputs:
> 
> args = -Fourier -twopass
> basefile = <undefined>
> copyorigin = <undefined>
> environ = {}
> in_file = <undefined>
> in_weight_volume = <undefined>
> interp = <undefined>
> md1d_file = <undefined>
> num_threads = 1
> oned_file = <undefined>
> oned_matrix_save = <undefined>
> out_file = <undefined>
> outputtype = NIFTI_GZ
> timeshift = <undefined>
> verbose = <undefined>
> zpad = 4
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 524, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 642, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 750, in _run_command
>     raise NodeExecutionError(
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node motion_correct.
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
>     setattr(outputs, key, val)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330,
> in validate
>     value = super(File, self).validate(objekt, name, value, return_pathlike=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
>     self.error(objekt, name, str(value))
>   File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
>     raise TraitError(
> traits.trait_errors.TraitError: The 'oned_file' trait of a VolregOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/scratch1/03201/jbwexler/work_dir/mriqc/ds000238_sub-22/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds000238-mriqc..sourcedata..raw..sub-22..func..sub-22_task-slow12_run-1_bold.nii.gz/motion_correct/sub-22_task-slow12_run-1_bold.1D' <class 'str'> was specified.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 401, in run
>     outputs = self.aggregate_outputs(runtime)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
>     raise FileNotFoundError(msg)
> FileNotFoundError: No such file or directory '/scratch1/03201/jbwexler/work_dir/mriqc/ds000238_sub-22/mriqc_wf/funcMRIQC/fMRI_HMC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds000238-mriqc..sourcedata..raw..sub-22..func..sub-22_task-slow12_run-1_bold.nii.gz/motion_correct/sub-22_task-slow12_run-1_bold.1D' for output 'oned_file' of a Volreg interface

**Comment by jbwexler** [comment]
Same error for one subject in ds000149-mriqc

**Comment by jbwexler** [comment]
Similar error for sub-09 in ds000011. Turns out due to a corrupted bold file.
