### ISSUE TITLE
ds000007-mriqc: "Expected dimension is 4D and you provided a 3D image"

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#46]
Just for sub-18. I suspect it may have to do with the T1w https://openneuro.org/datasets/ds000007/versions/00001/file-display/sub-18:anat:sub-18_T1w.nii.gz

> Node: mriqc_wf.funcMRIQC.ICA
> Working directory: /scratch1/03201/jbwexler/work_dir/mriqc/ds000007_sub-18/mriqc_wf/funcMRIQC/_in_file_..scratch1..03201..jbwexler..openneuro_derivatives..derivatives..mriqc..ds000007-mriqc..sourcedata..raw..sub-18..func..sub-18_task-stopvocal_run-1_bold.nii.gz/ICA
> 
> Node inputs:
> 
> ICs = <undefined>
> approach = <undefined>
> args = <undefined>
> bg_image = <undefined>
> bg_threshold = <undefined>
> compress_report = False
> cov_weight = <undefined>
> dim = <undefined>
> dim_est = <undefined>
> environ = {'FSLOUTPUTTYPE': 'NIFTI_GZ'}
> epsilon = <undefined>
> epsilonS = <undefined>
> in_files = <undefined>
> log_power = <undefined>
> mask = <undefined>
> max_restart = <undefined>
> maxit = <undefined>
> migp = <undefined>
> migpN = <undefined>
> migp_factor = <undefined>
> migp_shuffle = <undefined>
> mix = <undefined>
> mm_thresh = <undefined>
> no_bet = True
> no_mask = True
> no_mm = True
> non_linearity = <undefined>
> num_ICs = <undefined>
> out_all = <undefined>
> out_dir = <undefined>
> out_mean = <undefined>
> out_orig = <undefined>
> out_pca = <undefined>
> out_report = melodic_reportlet.svg
> out_stats = <undefined>
> out_unmix = <undefined>
> out_white = <undefined>
> output_type = NIFTI_GZ
> pbsc = <undefined>
> rem_cmp = <undefined>
> remove_deriv = <undefined>
> report = <undefined>
> report_maps = <undefined>
> report_mask = <undefined>
> s_con = <undefined>
> s_des = <undefined>
> sep_vn = <undefined>
> sep_whiten = <undefined>
> smode = <undefined>
> t_con = <undefined>
> t_des = <undefined>
> tr_sec = <undefined>
> update_mask = <undefined>
> var_norm = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 429, in run
>     runtime = self._post_run_hook(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/reportlets/segmentation.py", line 169, in _post_run_hook
>     self._generate_report()
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/reportlets/segmentation.py", line 184, in _generate_report
>     plot_melodic_components(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/viz/utils.py", line 637, in plot_melodic_components
>     for i, img in enumerate(iter_img(os.path.join(melodic_dir, "melodic_IC.nii.gz"))):
>   File "/opt/conda/lib/python3.8/site-packages/nilearn/image/image.py", line 696, in iter_img
>     return check_niimg_4d(imgs, return_iterator=True)
>   File "/opt/conda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 379, in check_niimg_4d
>     return check_niimg(niimg, ensure_ndim=4, return_iterator=return_iterator,
>   File "/opt/conda/lib/python3.8/site-packages/nilearn/_utils/niimg_conversions.py", line 296, in check_niimg
>     raise DimensionError(len(niimg.shape), ensure_ndim)
> nilearn._utils.exceptions.DimensionError: Input data has incompatible dimensionality: Expected dimension is 4D and you provided a 3D image. See http://nilearn.github.io/manipulating_images/input_output.html.

**Comment by jbwexler** [comment]
This seems to have been fixed in newer versions of mriqc.
