### ISSUE TITLE
ds003550-fmriprep: "IndexError: boolean index did not match indexed array along dimension 0; dimension is 39 but corresponding boolean dimension is 64"

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#70]
Only happened for sub-sc002:

> sub-sc001: 07:21:45 succeeded
> Node: fmriprep_23_0_wf.single_subject_sc002_wf.fmap_preproc_wf.fmap_reports_wf_auto_00001.fmap_rpt
> Working directory: /scratch1/03201/jbwexler/work_dir/fmriprep/ds003550_sub-sc002/fmriprep_23_0_wf/single_subject_sc002_wf/fmap_preproc_wf/fmap_reports_wf_auto_00001/fmap_rpt
> 
> Node inputs:
> 
> apply_mask = False
> fieldmap = <undefined>
> mask = <undefined>
> max_alpha = 0.7
> moving = <undefined>
> moving_label = Fieldmap (Hz)
> out_report = report.svg
> reference = <undefined>
> reference_label = Reference
> show = 1
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
>     raise NodeExecutionError(msg)
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node fmap_rpt.
> 
> Traceback:
>         Traceback (most recent call last):
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 398, in run
>             runtime = self._post_run_hook(runtime)
>           File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/mixins/reporting.py", line 50, in _post_run_hook
>             self._generate_report()
>           File "/opt/conda/lib/python3.9/site-packages/sdcflows/interfaces/reportlets.py", line 103, in _generate_report
>             abs(np.percentile(fmapdata[maskdata], 99.8)),
>         IndexError: boolean index did not match indexed array along dimension 0; dimension is 39 but corresponding boolean dimension is 64

**Comment by jbwexler** [comment]
Just ran into this for ds003772 sub-tq315. @effigies any ideas?
