### ISSUE TITLE
ds002574-fmriprep (minimal mode): "Error occurred when preparing to run topup"

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#78]
For all subjects:

> Traceback (most recent call last):
> ,  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
> ,  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
>     result = self._run_interface(execute=True)
> ,  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
>     return self._run_command(execute)
> ,  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
>     raise NodeExecutionError(msg)
> ,nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node topup.
> 
> Cmdline:
> 	topup --config=/opt/conda/envs/fmriprep/lib/python3.10/site-packages/sdcflows/data/flirtsch/b02b0.cnf --datain=/scratch1/03201/jbwexler/work_dir/fmriprep/ds002574_sub-01/fmriprep_23_2_wf/fit_sub_01_wf/fmap_preproc_wf/wf_auto_00036/topup/sub-01_ses-03_task-prf_run-14_bold_average_merged_sliced_volregLAS_encfile.txt --imain=/scratch1/03201/jbwexler/work_dir/fmriprep/ds002574_sub-01/fmriprep_23_2_wf/fit_sub_01_wf/fmap_preproc_wf/wf_auto_00036/to_las/sub-01_ses-03_task-prf_run-14_bold_average_merged_sliced_volregLAS.nii.gz --out=sub-01_ses-03_task-prf_run-14_bold_average_merged_sliced_volregLAS_base --iout=sub-01_ses-03_task-prf_run-14_bold_average_merged_sliced_volregLAS_corrected.nii.gz --fout=sub-01_ses-03_task-prf_run-14_bold_average_merged_sliced_volregLAS_field.nii.gz --jacout=jac --logout=sub-01_ses-03_task-prf_run-14_bold_average_merged_sliced_volregLAS_topup.log --rbmout=xfm --dfout=warpfield
> Stdout:
> 
> Stderr:
> 	Error occurred when preparing to run topup
> 	Exception thrown with message: Topup::TopupScan::TopupScan: third element of pevec must be zero
> Traceback:
> 	Traceback (most recent call last):
> 	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
> 	    setattr(outputs, key, val)
> 	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
> 	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
> 	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
> 	    self.error(objekt, name, str(value))
> 	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
> 	    raise TraitError(
> 	traits.trait_errors.TraitError: The 'out_movpar' trait of a TOPUPOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002574_sub-01/fmriprep_23_2_wf/fit_sub_01_wf/fmap_preproc_wf/wf_auto_00036/topup/sub-01_ses-03_task-prf_run-14_bold_average_merged_sliced_volregLAS_base_movpar.txt' <class 'str'> was specified.
> 
> 	During handling of the above exception, another exception occurred:
> 
> 	Traceback (most recent call last):
> 	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 400, in run
> 	    outputs = self.aggregate_outputs(runtime)
> 	  File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
> 	    raise FileNotFoundError(msg)
> 	FileNotFoundError: No such file or directory '/scratch1/03201/jbwexler/work_dir/fmriprep/ds002574_sub-01/fmriprep_23_2_wf/fit_sub_01_wf/fmap_preproc_wf/wf_auto_00036/topup/sub-01_ses-03_task-prf_run-14_bold_average_merged_sliced_volregLAS_base_movpar.txt' for output 'out_movpar' of a TOPUP interface

**Comment by jbwexler** [comment]
I reran with a recent version of fmriprep and got these errors again.
