### ISSUE TITLE
ds000164 mriqc: ValueError: Axis limits cannot be NaN or Inf

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#8]
Happened for every subject. Here's an example err log:

> (main) login4.frontera(1066)$ cat /scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds000164-mriqc/.reproman/jobs/local/20220216-082803-4fd2/stderr.18
> Traceback (most recent call last):
>   File "/opt/conda/bin/mriqc", line 8, in <module>
>     sys.exit(main())
>   File "/opt/conda/lib/python3.8/site-packages/mriqc/cli/run.py", line 95, in main
>     mriqc_wf.run(**config.nipype.get_plugin())
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
>     runner.run(execgraph, updatehash=updatehash, config=self.config)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 164, in run
>     self._clean_queue(jobid, graph, result=result)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
>     raise RuntimeError("".join(result["traceback"]))
> RuntimeError: Traceback (most recent call last):
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
>     result = self._interface.run(cwd=outdir)
>   File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 429, in run
>     runtime = self._post_run_hook(runtime)
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/reportlets/segmentation.py", line 169, in _post_run_hook
>     self._generate_report()
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/interfaces/reportlets/segmentation.py", line 184, in _generate_report
>     plot_melodic_components(
>   File "/opt/conda/lib/python3.8/site-packages/niworkflows/viz/utils.py", line 695, in plot_melodic_components
>     ax3.set_xlim([f[0], f.max()])
>   File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 3522, in set_xlim
>     left = self._validate_converted_limits(left, self.convert_xunits)
>   File "/opt/conda/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 3439, in _validate_converted_limits
>     raise ValueError("Axis limits cannot be NaN or Inf")
> ValueError: Axis limits cannot be NaN or Inf

**Comment by jbwexler** [comment]
Seeing this for every subject in ds000200-mriqc as well. @oesteban any ideas?
