### ISSUE TITLE
ds002169_fmriprep: "ITK ERROR: ITK only supports orthonormal direction cosines."

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#80]
About half the subjects produced errors like this:

> Node: fmriprep_23_2_wf.sub_18_wf.fmap_preproc_wf.wf_auto_00006.brainextraction_wf.n4
> Working directory: /node_tmp/work_dir/fmriprep/ds002169_sub-18/fmriprep_23_2_wf/sub_18_wf/fmap_preproc_wf/wf_auto_00006/brainextraction_wf/n4
> 
> Node inputs:
> 
> args = <undefined>
> bias_image = <undefined>
> bspline_fitting_distance = <undefined>
> bspline_order = <undefined>
> convergence_threshold = 1e-07
> copy_header = True
> dimension = 3
> environ = {'NSLOTS': '8'}
> histogram_sharpening = <undefined>
> input_image = <undefined>
> mask_image = <undefined>
> n_iterations = [50, 50, 50, 50, 50]
> num_threads = 8
> output_image = <undefined>
> rescale_intensities = False
> save_bias = False
> shrink_factor = 4
> weight_image = <undefined>
> 
> Traceback (most recent call last):
>   File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
>     result["result"] = node.run(updatehash=updatehash)
>   File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
>     result = self._run_interface(execute=True)
>   File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
>     return self._run_command(execute)
>   File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
>     raise NodeExecutionError(msg)
> nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node n4.
> 
> Cmdline:
>         N4BiasFieldCorrection -d 3 --input-image /node_tmp/work_dir/fmriprep/ds002169_sub-18/fmriprep_23_2_wf/sub_18_wf/fmap_preproc_wf/wf_auto_00006/brainextraction_wf/clipper_pre/clipped.nii.gz --convergence [ 50x50x50x50x50, 1e-07 ] --output clipped_corrected.nii.gz --shrink-factor 4
> Stdout:
> 
> Stderr:
>         Exception caught during reference file reading
> 
>         itk::ExceptionObject (0x56132065fe50)
>         Location: "unknown"
>         File: /home/conda/feedstock_root/build_artifacts/libitk_1692713128928/work/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
>         Line: 2016
>         Description: ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!
> 
>          file /node_tmp/work_dir/fmriprep/ds002169_sub-18/fmriprep_23_2_wf/sub_18_wf/fmap_preproc_wf/wf_auto_00006/brainextraction_wf/clipper_pre/clipped.nii.gz
>         Segmentation fault
> Traceback:
>         Traceback (most recent call last):
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
>             setattr(outputs, key, val)
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
>             value = super(File, self).validate(objekt, name, value, return_pathlike=True)
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
>             self.error(objekt, name, str(value))
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/traits/base_trait_handler.py", line 74, in error
>             raise TraitError(
>         traits.trait_errors.TraitError: The 'output_image' trait of a N4BiasFieldCorrectionOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/node_tmp/work_dir/fmriprep/ds002169_sub-18/fmriprep_23_2_wf/sub_18_wf/fmap_preproc_wf/wf_auto_00006/brainextraction_wf/n4/clipped_corrected.nii.gz' <class 'str'> was specified.
> 
>         During handling of the above exception, another exception occurred:
> 
>         Traceback (most recent call last):
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 398, in run
>             runtime = self._post_run_hook(runtime)
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/mixins/fixheader.py", line 127, in _post_run_hook
>             outputs = self.aggregate_outputs(runtime=runtime).get_traitsfree()
>           File "/opt/conda/envs/fmriprep/lib/python3.10/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
>             raise FileNotFoundError(msg)
>         FileNotFoundError: No such file or directory '/node_tmp/work_dir/fmriprep/ds002169_sub-18/fmriprep_23_2_wf/sub_18_wf/fmap_preproc_wf/wf_auto_00006/brainextraction_wf/n4/clipped_corrected.nii.gz' for output 'output_image' of a N4BiasFieldCorrection interface

**Comment by jbwexler** [comment]
I'm seeing similar issues in ds002316.
