### ISSUE TITLE
ds004493-fmriprep: "Extreme value 9.23e+04 detected in spline coefficients."

### ISSUE THREAD

**Issue by jbwexler** [poldracklab/tacc-openneuro#96]
All subjects:

```
Node: fmriprep_24_1_wf.sub_09_wf.fmap_preproc_wf.wf_auto_00004.bs_filter
Working directory: /node_tmp/work_dir/fmriprep/ds004493_sub-09/fmriprep_24_1_wf/sub_09_wf/fmap_preproc_wf/wf_auto_00004/bs_filter

Node inputs:

bs_spacing = [(100.0, 100.0, 40.0), (16.0, 16.0, 10.0)]
debug = False
extrapolate = True
in_data = <undefined>
in_mask = <undefined>
recenter = False
ridge_alpha = 0.0001
zooms_min = 1.0

Traceback (most recent call last):
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node bs_filter.

Traceback:
        Traceback (most recent call last):
          File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/nipype/interfaces/base/core.py", line 397, in run
            runtime = self._run_interface(runtime)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/opt/conda/envs/fmriprep/lib/python3.11/site-packages/sdcflows/interfaces/bspline.py", line 225, in _run_interface
            raise RuntimeError(
        RuntimeError: Spline fit of input file /node_tmp/work_dir/fmriprep/ds004493_sub-09/fmriprep_24_1_wf/sub_09_wf/fmap_preproc_wf/wf_auto_00004/zooms_field/fmap_syn0Warp_Hz_trans.nii.gz failed. Extreme value 9.23e+04 detected in spline coefficients.
```

**Comment by jbwexler** [comment]
Expected to be fixed in the next release.
